version: "3.5"

services:
  server:
    container_name: server
    build: ./food-admin/
    env_file:
      - ./.env
    environment:
      - NODE_ENV=.dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    # volumes:
    #   - ./food-admin/.prod.env:/app/.prod.env
    networks:
      - postgres
    

  db:
    container_name: foodbase
    image: postgis/postgis:16-master
    restart: always
    environment:
      - POSTGRES_DB=FoodBase
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - postgres
    
  app:
    container_name: app
    image: dimad2602/flutter_env_new:latest
    
    env_file:
      - ./.env
    environment:
      - BACKEND_APIURL=http://diploma.punkrockov.ru:${APP_PORT}
    networks:
      - postgres
    ports: 
      - 80:80

volumes:
  database: 
    
networks:
  postgres:
    driver: bridge