version: "3.5"

services:
  server:
    build: ./food-admin/
    ports:
      - 3000:4000
    volumes:
      - ./food-admin/.prod.env:/app/.prod.env
    networks:
      - postgres
    

  db:
    container_name: foodbase
    image: postgis/postgis:16-master
    restart: always
    environment:
      - POSTGRES_DB=FoodBase
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - postgres
    
volumes:
  database: 
    
networks:
  postgres:
    driver: bridge